# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7495f90762356672f9fe3c5c14d2e87cf2e7618d92a1c563ced8a031c521dbc8a9d6e9d38c8ec14219a80cef016c48469f5e65f94d5bd5ddf729cf10ab0e2f4d

test:
  secret_key_base: 2613e5240fb4d8ca170915171047a8d469b4d28a0a414050d80b4f5df7a2986520aefa156725e4a78023f4a5653da561ad1ed66f415214e8f838f0e9a024d6eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
